/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vue_controleur;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import modele.*;

/**
 *
 * @author p1203723
 */
public class FenetreDemineur extends javax.swing.JFrame {
    
    private OptionsFrame optionsFrame;
    private Dimension tailleEcran;
    
    public JeuDeDemineur jeu;
    
    /**
     * Creates new form FenetreDemineur
     */
    public FenetreDemineur() {
        tailleEcran = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        jeu = new JeuDeDemineur();
        optionsFrame = new OptionsFrame(this, jeu.options);
        
        initComponents();
        InfoPanel infoPanel = new InfoPanel();
        panneauInfo.add(infoPanel);
        jeu.addObserver(infoPanel);
        resetVue();
    }
    
    public void resetVue() {
        panneauJeu.removeAll();
        initCasesVue();
        panneauJeu.updateUI();
    }

    private void quitter()
    {
        dispose();
    }

    private void initCasesVue() {
        int longueur = jeu.grille.getLongueur();
        int largeur = jeu.grille.getLargeur();
        panneauJeu.setLayout(new GridLayout(longueur, largeur));
        
        int lo, la = -1;
        for(int i = 0; i < longueur*largeur; i++) {
            lo = i%longueur;
            if(lo == 0)
                la++;
            CaseVue j = new CaseVue(lo, la);
            j.setLayout(new BorderLayout());
            j.setBorder(new SoftBevelBorder(BevelBorder.RAISED));
            j.setSize(new Dimension(35,35));
            j.setMaximumSize(new Dimension(35,35));
            j.addMouseListener(new MouseListener() {

                @Override
                public void mouseClicked(MouseEvent e) {
                    
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    CaseVue c = (CaseVue)e.getComponent();
                    if(SwingUtilities.isLeftMouseButton(e)) {
                        boolean b = jeu.clicGauche(c.coord_x, c.coord_y);
                        // le joueur a découvert une bombe
                        if(b)
                        {
                            jeu.grille.toutReveler();
                            int reponse = JOptionPane.showConfirmDialog(null, "Oh oh ! C'était une mine ! Vous avez perdu. Voulez-vous recommencez"
                                    + " une partie ?","Perdu !",JOptionPane.YES_NO_OPTION);
                            switch(reponse)
                            {
                                case JOptionPane.YES_OPTION:
                                    jeu.setJeu();
                                    resetVue();
                                    break;
                            }
                        }
                        else
                        {
                            
                        }
                    }
                    if(SwingUtilities.isRightMouseButton(e)) {
                        jeu.clicDroit(c.coord_x, c.coord_y);
                    }
                    if(jeu.victoire())
                    {
                        jeu.grille.toutReveler();
                        int reponse = JOptionPane.showConfirmDialog(null, "Félicitations ! Vous avez bravé les mines ! Voulez-vous relancer une partie ?","C'est gagné !",JOptionPane.YES_NO_OPTION);
                            switch(reponse)
                            {
                                case JOptionPane.YES_OPTION:
                                    jeu.setJeu();
                                    resetVue();
                                    break;
                            }
                    }
                    
                   
                    
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                   
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    
                }
            });
            jeu.grille.cases[lo][la].addObserver(j);
            panneauJeu.add(j);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        panneauInfo = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        panneauJeu = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        itemNouvellePartie = new javax.swing.JMenuItem();
        itemOptions = new javax.swing.JMenuItem();
        itemQuitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(this.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));
        getContentPane().add(filler2);

        panneauInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panneauInfo.setLayout(new javax.swing.BoxLayout(panneauInfo, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panneauInfo);
        getContentPane().add(filler1);

        panneauJeu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panneauJeu.setMaximumSize(new java.awt.Dimension(875, 875));
        panneauJeu.setName(""); // NOI18N

        javax.swing.GroupLayout panneauJeuLayout = new javax.swing.GroupLayout(panneauJeu);
        panneauJeu.setLayout(panneauJeuLayout);
        panneauJeuLayout.setHorizontalGroup(
            panneauJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        panneauJeuLayout.setVerticalGroup(
            panneauJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        getContentPane().add(panneauJeu);

        jMenu.setText("Jeu");
        jMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu.setFocusable(false);

        itemNouvellePartie.setText("Nouvelle Partie");
        itemNouvellePartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNouvellePartieActionPerformed(evt);
            }
        });
        jMenu.add(itemNouvellePartie);

        itemOptions.setText("Opions");
        itemOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOptionsActionPerformed(evt);
            }
        });
        jMenu.add(itemOptions);

        itemQuitter.setText("Quitter");
        itemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQuitterActionPerformed(evt);
            }
        });
        jMenu.add(itemQuitter);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        tailleEcran = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        
    }//GEN-LAST:event_formComponentResized

    private void itemNouvellePartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNouvellePartieActionPerformed
        jeu.setJeu();
        resetVue();
    }//GEN-LAST:event_itemNouvellePartieActionPerformed

    private void itemOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOptionsActionPerformed
        optionsFrame.setVisible(true);
    }//GEN-LAST:event_itemOptionsActionPerformed

    private void itemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQuitterActionPerformed
        jeu.cancelThread();
        dispose();
    }//GEN-LAST:event_itemQuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDemineur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDemineur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDemineur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDemineur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDemineur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JMenuItem itemNouvellePartie;
    private javax.swing.JMenuItem itemOptions;
    private javax.swing.JMenuItem itemQuitter;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel panneauInfo;
    private javax.swing.JPanel panneauJeu;
    // End of variables declaration//GEN-END:variables
}
